update

diff --git a/.github/workflows/e2eTests.yml b/.github/workflows/e2eTests.yml
--- a/.github/workflows/e2eTests.yml
+++ b/.github/workflows/e2eTests.yml
@@ -18,6 +18,39 @@ jobs:
           check-latest: true
       - name: Run tests
         continue-on-error: true
+        run: mvn test "-DexecutionAddress=local" "-DtargetOperatingSystem=WINDOWS" "-DtargetBrowserName=MicrosoftEdge" "-DheadlessExecution=true" "-DgenerateAllureReportArchive=true" "-Dtest=${TESTING_SCOPE}" "-DclickUsingJavascriptWhenWebDriverClickFails=true" "-DwhenToTakePageSourceSnapshot=FailuresOnly"
+      - name: Upload Allure Report as Pipeline Artifact
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: Windows_Edge_Local_Allure
+          path: "generatedReport_*.zip"
+      - name: Upload Execution Summary Report as Pipeline Artifact
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: Windows_Edge_Local_Summary
+          path: "execution-summary/ExecutionSummaryReport_*.html"
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'target/surefire-reports/TEST-*.xml'
+
+  LINUX_Chrome_Local:
+    runs-on: windows-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'zulu'
+          cache: 'maven'
+          check-latest: true
+      - name: Run tests
+        continue-on-error: true
         run: mvn test "-DexecutionAddress=local" "-DtargetOperatingSystem=LINUX" "-DtargetBrowserName=Chrome" "-DheadlessExecution=true" "-DgenerateAllureReportArchive=true" "-Dtest=${TESTING_SCOPE}" "-DclickUsingJavascriptWhenWebDriverClickFails=true" "-DwhenToTakePageSourceSnapshot=FailuresOnly"
       - name: Upload Allure Report as Pipeline Artifact
         if: always()
@@ -36,3 +69,4 @@ jobs:
         if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: 'target/surefire-reports/TEST-*.xml'
+
